### ISSUE TITLE
Error when executing `:GitAbra`

### ISSUE THREAD

**Issue by ChrisPenner** [Odie/gitabra#1]
Tried installing (with Packer: `use 'Odie/gitabra'`) and running `:GitAbra` just returns this error:

```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'gitabra_status' (a nil value)
```

I'm on NVIM v0.5.0-dev+314b2222

Cheers

**Comment by Odie** [comment]
hmmm!

I tried running with a minimal packer config, but it worked fine. I'm not quite able to repro this locally.
```
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
 	use {'wbthomason/packer.nvim', opt = true}
	use 'Odie/gitabra'
end)
```

The error you posted suggests that gitabra *is* loaded, but its entry function is missing.
Do you mind posting the result of this command here?
```
:lua print(vim.inspect(require('gitabra')))
```

**Comment by krage** [comment]
Seems like root cause might be a missing module?
```
:lua print(vim.inspect(require('gitabra')))
```
just prints `{}` here but after a fresh start trying 
```
:lua print(vim.inspect(require('gitabra.git_status')))
``` 
instead produces an error followed by the usual stack of paths searched/files checked:
```
E5108: Error executing lua ...e\pack\packer\start\gitabra\lua\gitabra\patch_parser.lua:1: module 'lpeg' not found
```

**Comment by Odie** [comment]
Oh! Thanks for tracking this down!

That should be fixed just by removing the first line of lua/gitabra/patch_parser.lua. I must have left that require in by accident.

Will push out an update when I get back to my computer.

**Comment by Odie** [comment]
Just pushed a new commit that should fix this problem.

**Comment by ChrisPenner** [comment]
Fixed 👌🏼
