### ISSUE TITLE
The ability to configure icons

### ISSUE THREAD

**Issue by Shatur** [Odie/gitabra#7]
Could you add the ability to configure status icons?
![изображение](https://user-images.githubusercontent.com/22453358/117513436-59b83180-af9a-11eb-8432-0b14e2378cf4.png)

**Comment by Odie** [comment]
Will do! @sevensidedmarble already took a shot at this with #5. I’ll try to stick everything in a config map soon. :)

**Comment by Odie** [comment]
Hi there!

This has been implemented in 30cc5e5e5e4b3af46684894dabc7c94c5e857a95.
The readme has also been updated to show how to figure the status icons.
Let me know if you run into any problems.

**Comment by Shatur** [comment]
Thank you!
